export const escrowAbi = [
  {
    type: "function",
    name: "asset",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "deploymentId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "devCo",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "securityReserve",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "verifierAt",
    stateMutability: "view",
    inputs: [{ name: "index", type: "uint256" }],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "verifierSetHash",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "eip712Domain",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "fields", type: "bytes1" },
      { name: "name", type: "string" },
      { name: "version", type: "string" },
      { name: "chainId", type: "uint256" },
      { name: "verifyingContract", type: "address" },
      { name: "salt", type: "bytes32" },
      { name: "extensions", type: "uint256[]" },
    ],
  },
  {
    type: "function",
    name: "nextBountyId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "claimable",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "amount", type: "uint256" }],
  },
  {
    type: "function",
    name: "commitments",
    stateMutability: "view",
    inputs: [
      { name: "bountyId", type: "uint256" },
      { name: "solver", type: "address" },
    ],
    outputs: [{ name: "commitment", type: "bytes32" }],
  },
  {
    type: "function",
    name: "isSolvent",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "requiredFunding",
    stateMutability: "pure",
    inputs: [
      { name: "reward", type: "uint256" },
      { name: "verifierFee", type: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "minimumVerifierFee",
    stateMutability: "pure",
    inputs: [{ name: "reward", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "maximumVerifierFee",
    stateMutability: "pure",
    inputs: [{ name: "reward", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getBounty",
    stateMutability: "view",
    inputs: [{ name: "bountyId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "sponsor", type: "address" },
          { name: "refundRecipient", type: "address" },
          { name: "winner", type: "address" },
          { name: "reward", type: "uint256" },
          { name: "verifierFee", type: "uint256" },
          { name: "fundedAmount", type: "uint256" },
          { name: "commitDeadline", type: "uint64" },
          { name: "claimDeadline", type: "uint64" },
          { name: "status", type: "uint8" },
          { name: "profileId", type: "bytes32" },
          { name: "specificationHash", type: "bytes32" },
          { name: "termsHash", type: "bytes32" },
          { name: "resultDigest", type: "bytes32" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "createBounty",
    stateMutability: "payable",
    inputs: [
      {
        name: "request",
        type: "tuple",
        components: [
          { name: "refundRecipient", type: "address" },
          { name: "reward", type: "uint256" },
          { name: "verifierFee", type: "uint256" },
          { name: "commitDeadline", type: "uint64" },
          { name: "claimDeadline", type: "uint64" },
          { name: "profileId", type: "bytes32" },
          { name: "specificationHash", type: "bytes32" },
          { name: "termsHash", type: "bytes32" },
        ],
      },
    ],
    outputs: [{ name: "bountyId", type: "uint256" }],
  },
  {
    type: "function",
    name: "commit",
    stateMutability: "nonpayable",
    inputs: [
      { name: "bountyId", type: "uint256" },
      { name: "commitment", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "claim",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "result",
        type: "tuple",
        components: [
          { name: "bountyId", type: "uint256" },
          { name: "solver", type: "address" },
          { name: "resultDigest", type: "bytes32" },
          { name: "salt", type: "bytes32" },
        ],
      },
      {
        name: "signatures",
        type: "tuple[2]",
        components: [
          { name: "verifierIndex", type: "uint8" },
          { name: "signature", type: "bytes" },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "refund",
    stateMutability: "nonpayable",
    inputs: [{ name: "bountyId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "withdraw",
    stateMutability: "nonpayable",
    inputs: [
      { name: "destination", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
  },
] as const;

export const erc20Abi = [
  {
    type: "function",
    name: "symbol",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "decimals",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "allowance",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
] as const;

export const acceptedResultTypes = {
  AcceptedResult: [
    { name: "deploymentId", type: "bytes32" },
    { name: "bountyId", type: "uint256" },
    { name: "solver", type: "address" },
    { name: "commitment", type: "bytes32" },
    { name: "resultDigest", type: "bytes32" },
    { name: "reward", type: "uint256" },
    { name: "verifierFee", type: "uint256" },
    { name: "profileId", type: "bytes32" },
    { name: "specificationHash", type: "bytes32" },
    { name: "termsHash", type: "bytes32" },
    { name: "verifierSetHash", type: "bytes32" },
    { name: "claimDeadline", type: "uint64" },
  ],
} as const;
